'use strict';
const A=require('./_assert.js'); const fs=require('node:fs'); const os=require('node:os'); const path=require('node:path');
const {rawEvent,normalize,run,exportPublicHealth,generateFindingIndex,validateFinding,validateReceipt}=require('../sidecar/pauli-icm-architect.js');
const events=JSON.parse(fs.readFileSync('fixtures/pauli-icm/historical-events.json','utf8'));
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'pauli-icm-')); const first=run(events,tmp,{generated_at:'2026-09-15T09:40:00Z'}); const tmp2=fs.mkdtempSync(path.join(os.tmpdir(),'pauli-icm-')); const second=run(events,tmp2,{generated_at:'2026-09-15T09:40:00Z'});
A.eq(first.proposals.findings.length,4,'shadow replay catches four grounded findings'); A.ok(first.manifest.events.every(e=>e.schema_valid&&e.verification_level==='shape-only'&&!e.verified),'historical fixtures are honestly shape-only'); A.eq(first.brief.cost_usd,0,'verified shadow costs $0'); A.eq(JSON.stringify(first),JSON.stringify(second),'fixed input gives byte-stable logical output');
A.ok(first.proposals.findings.every(f=>f.approval_required&&validateFinding(f)),'every proposal conforms and needs approval'); A.ok(first.proposals.findings.some(f=>f.id.startsWith('false-pass-')),'false pass cross-examined'); A.ok(first.proposals.findings.some(f=>f.id.startsWith('mutation-')),'watcher mutation flagged');
const H='sha256:'+'d'.repeat(64), FR='fixture://sha256/'+'e'.repeat(64); const mk=(id,type,payload,source='fixture-health',evidence_refs=[FR])=>rawEvent({observed_at:'2026-09-15T09:40:00Z',source,type,sensitivity:'shared',payload,evidence_refs});
const live=run([mk('fixture-health','health',{status:'ok',dependencies:{coolify:'unreachable'}})],fs.mkdtempSync(path.join(os.tmpdir(),'live-')),{generated_at:'2026-09-15T09:40:00Z'}); A.ok(live.proposals.findings.some(f=>f.id.startsWith('dependency-health-')),'nested dependency failure reported');
for(const type of ['mission','result','evaluation','health']) A.throws(()=>normalize(mk(`paid-${type}`,type,{paid_route:true})),/paid route denied/,`paid route denied for ${type}`);
for(const payload of [{meta:{paid_route:true}},{billing:{cost_usd:10}},{routing:{provider:'openai',model:'gpt-6'}}]) A.throws(()=>normalize(rawEvent({...events[0],event_id:'nested-paid',payload})),/paid (route|cost|model) denied/,'nested paid marker denied before schema receipt');
for(const payload of [{evidence:[{type:'artifact',ref:'artifact://sha256/'+ 'f'.repeat(64),address:'123 Main'}]},{evidence:[{type:'artifact',ref:'artifact://sha256/'+ 'f'.repeat(64),email:'a@b.test'}]},{evidence:[{type:'artifact',ref:'artifact://sha256/'+ 'f'.repeat(64),dob:'2000-01-01'}]},{evidence:[{type:'artifact',ref:'artifact://sha256/'+ 'f'.repeat(64),price_usd:1}]},{evidence:[{type:'artifact',ref:'artifact://sha256/'+ 'f'.repeat(64),billing_amount:1}]},{evidence:[{type:'artifact',ref:'artifact://sha256/'+ 'f'.repeat(64),is_billable:true}]},{evidence:[{type:'artifact',ref:'artifact://sha256/'+ 'f'.repeat(64),spend:1}]},{evidence:[{type:'artifact',ref:'artifact://sha256/'+ 'f'.repeat(64),route_name:'premium'}]}]) A.throws(()=>normalize(rawEvent({...events[1],event_id:'array-hole',payload})),/secret\/private|paid (route|cost|model)|payload field not allowlisted/,'array evidence hole rejected');
const good=events[0]; A.throws(()=>normalize({...good,source:'attacker'}),/source not allowlisted/,'unknown source rejected'); A.throws(()=>normalize({...good,evidence_refs:[]}),/non-empty/,'empty evidence rejected'); A.throws(()=>normalize({...good,evidence_refs:['https://evil.invalid/x']}),/unverifiable/,'unbound evidence rejected'); A.throws(()=>normalize({...good,content_hash:'sha256:'+'0'.repeat(64)}),/mismatch/,'tampered hash rejected'); A.throws(()=>normalize({...good,content_hash:undefined}),/required/,'missing hash rejected'); const opaqueMission=rawEvent({...good,payload:{...good.payload,mission_id:'3235550123'}}); A.throws(()=>normalize(opaqueMission),/secret\/private|invalid id/,'bare phone cannot use mission id channel'); const opaqueEvent={...good,event_id:'3235550123'}; A.throws(()=>normalize(opaqueEvent),/secret\/private|content-derived/,'bare phone cannot use event id channel'); const opaqueRef=rawEvent({...events[1],payload:{...events[1].payload,evidence:[{type:'artifact',ref:'artifact://3235550123'}]}}); A.throws(()=>normalize(opaqueRef),/secret\/private|invalid reference/,'bare phone cannot use reference channel');
for(const payload of [{api_token:'x'},{apiKey:'x'},{note:'Bearer abc123'},{note:'Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ=='},{ssn:'123-45-6789'},{socialSecurityNumber:'123456789'},{nested:{password:'x'}},{note:'-----BEGIN PRIVATE KEY-----'},{contact_email:'a@b.test'},{phone:'+13235550123'},{home_address:'123 Main'},{card_number:'4242424242424242'},{note:'AIzaSyDUMMYEXAMPLEKEY1234567890'},{note:'eyJabcdefghijk.abcdefghijkl.abcdefghijk'}]) A.throws(()=>normalize(rawEvent({...good,event_id:'unsafe',payload})),/secret\/private data rejected/,`unsafe payload rejected ${JSON.stringify(payload)}`);
A.throws(()=>normalize({...good,authorization:'Bearer abc123'}),/unknown top-level|secret\/private/,'top-level auth rejected, not dropped'); A.throws(()=>normalize({...good,sensitivity:'private'}),/sensitivity/,'private sensitivity rejected');
A.throws(()=>normalize(mk('private','mission',{private_pi_data:true},'fixture-pi',[FR])),/secret\/private/,'private field pattern rejected at ingestion'); for(const summary of ['alice@example.com','+1 (323) 555-0123','123 Main Street','DOB: 2000-01-01','access code: 837492']){ const e=rawEvent({...events[1],event_id:'pii-string',payload:{mission_id:'m1',status:'done',evidence:[{type:'artifact',ref:'artifact://sha256/'+ 'f'.repeat(64),summary}]}}); A.throws(()=>normalize(e),/secret\/private|not allowlisted/,'PII/free text rejected from evidence '+summary); }
A.throws(()=>exportPublicHealth('https://evil.invalid/health','/tmp/nope'),/health source not allowlisted/,'arbitrary health host rejected synchronously');
const receiptRoot=fs.mkdtempSync(path.join(os.tmpdir(),'receipts-')); fs.cpSync('districts/pauli/icm-architect/runs/2026-09-15T094100Z-live-public-health/00_source/health',path.join(receiptRoot,'health'),{recursive:true}); A.eq(validateReceipt(receiptRoot,'health').status,200,'captured receipt validates'); fs.appendFileSync(path.join(receiptRoot,'health','response.json'),'\n'); A.throws(()=>validateReceipt(receiptRoot,'health'),/hash mismatch/,'receipt byte changes fail validation');
const committedInput=JSON.parse(fs.readFileSync('districts/pauli/icm-architect/runs/2026-09-15T094100Z-live-public-health/01_ingest/input-event.json')); A.ok(normalize(committedInput,{receiptRoot:'districts/pauli/icm-architect/runs/2026-09-15T094100Z-live-public-health/00_source'}).verified,'committed live input replays through validated receipts'); const mixedRoot='districts/pauli/icm-architect/runs/2026-09-15T094100Z-live-public-health/00_source'; const m1=run([events[0],committedInput],fs.mkdtempSync(path.join(os.tmpdir(),'mixed1-')),{receiptRoot:mixedRoot}); const m2=run([committedInput,events[0]],fs.mkdtempSync(path.join(os.tmpdir(),'mixed2-')),{receiptRoot:mixedRoot}); A.eq(m1.manifest.generated_at,m2.manifest.generated_at,'mixed live time is order-independent'); A.eq(m1.manifest.generated_at,committedInput.observed_at,'mixed run time derives from live event'); const urlOnly={...committedInput,evidence_refs:[committedInput.source]}; urlOnly.content_hash=require('../sidecar/pauli-icm-architect').rawEvent(urlOnly).content_hash; A.throws(()=>normalize(urlOnly,{receiptRoot:'districts/pauli/icm-architect/runs/2026-09-15T094100Z-live-public-health/00_source'}),/requires resolvable/,'URL-only live claim rejected'); const fake={...committedInput,evidence_refs:[committedInput.source,'receipt://runs/live-public-health/health/../../fake/request.json','receipt://runs/live-public-health/health/response.json']}; fake.content_hash=require('../sidecar/pauli-icm-architect').rawEvent(fake).content_hash; A.throws(()=>normalize(fake,{receiptRoot:'districts/pauli/icm-architect/runs/2026-09-15T094100Z-live-public-health/00_source'}),/unverifiable|unrecognized/,'traversing receipt URI rejected'); const fabricated={...committedInput,payload:{...committedInput.payload,version:'999-fabricated',dependencies:{coolify:'healthy',coolify_version:'999',services_count:999}}}; fabricated.content_hash=require('../sidecar/pauli-icm-architect').rawEvent(fabricated).content_hash; A.throws(()=>normalize(fabricated,{receiptRoot:'districts/pauli/icm-architect/runs/2026-09-15T094100Z-live-public-health/00_source'}),/does not match receipt/,'genuine receipt cannot verify fabricated payload'); const fakeTime=require('../sidecar/pauli-icm-architect').rawEvent({...committedInput,observed_at:'2026-12-31T00:00:00Z'}); A.throws(()=>normalize(fakeTime,{receiptRoot:'districts/pauli/icm-architect/runs/2026-09-15T094100Z-live-public-health/00_source'}),/not receipt-derived or fresh|content-derived/,'live time cannot be caller-fabricated'); const fakeIdentity={...committedInput,event_id:'health-now'}; A.throws(()=>normalize(fakeIdentity,{receiptRoot:'districts/pauli/icm-architect/runs/2026-09-15T094100Z-live-public-health/00_source'}),/content-derived|secret\/private/,'live identity cannot be caller-fabricated');
for(const n of [NaN,Infinity,-Infinity,-1,1.5]){const bad=rawEvent({...events[2],payload:{...events[2].payload,origin_evidence_count:n}});A.throws(()=>normalize(bad),/invalid count/,'invalid numeric count rejected '+n);}
const committedReceipts='districts/pauli/icm-architect/runs/2026-09-15T094100Z-live-public-health/00_source'; for(const n of ['health','protected-system-status','protected-fleet-missions']) A.ok(validateReceipt(committedReceipts,n).status>=200,'committed receipt validates '+n); const metaRoot=fs.mkdtempSync(path.join(os.tmpdir(),'meta-')); fs.cpSync(path.join(committedReceipts,'health'),path.join(metaRoot,'health'),{recursive:true}); const rq=JSON.parse(fs.readFileSync(path.join(metaRoot,'health/request.json'))); rq.request_headers.Authorization='Bearer fake'; fs.writeFileSync(path.join(metaRoot,'health/request.json'),JSON.stringify(rq)); A.throws(()=>validateReceipt(metaRoot,'health'),/metadata mismatch/,'receipt auth metadata enforced');
const fr=fs.mkdtempSync(path.join(os.tmpdir(),'findings-')); for(const s of ['open','accepted','rejected','superseded'])fs.mkdirSync(path.join(fr,s)); for(const f of first.proposals.findings)fs.writeFileSync(path.join(fr,'open',f.id+'.json'),JSON.stringify(f)); const rows=generateFindingIndex(fr); A.eq(rows.length,4,'finding index generated from conforming records'); fs.writeFileSync(path.join(fr,'open','bad.json'),'{}'); A.throws(()=>generateFindingIndex(fr),/status|missing/,'generator rejects malformed record'); const fresh=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'fresh-')),'missing-findings'); A.eq(generateFindingIndex(fresh).length,0,'generator creates all lifecycle dirs on fresh checkout');
for(const stage of ['01_ingest','02_verify','03_cross-examine','04_propose','05_report']) A.ok(fs.existsSync(path.join(tmp,stage,'output')),'stage output exists '+stage); A.report();
