'use strict';
const A=require('./_assert.js'); const fs=require('node:fs'); const path=require('node:path'); const os=require('node:os'); const {validateFinding,generateFindingIndex}=require('../sidecar/pauli-icm-architect');
const root='districts/pauli/icm-architect'; const entry=fs.readFileSync(path.join(root,'CLAUDE.md'),'utf8');
A.ok(entry.split('\n').length<60,'entry router stays under 60 lines'); A.ok(entry.includes('observe-and-propose-only'),'role visible at entry');
for(const stage of ['01_ingest','02_verify','03_cross-examine','04_propose','05_report']){ const p=path.join(root,'_templates/watch-run',stage,'CONTEXT.md'); const s=fs.readFileSync(p,'utf8'); for(const h of ['## Inputs','## Process','## Outputs','## Human check']) A.ok(s.includes(h),`${stage} has ${h}`); }
const locks=JSON.parse(fs.readFileSync(path.join(root,'_meta/contracts.lock.json'),'utf8')); A.eq(locks.sources.pauli_starnet.sha,'826636afd019db686c8700f57aeb6d2ee0cde474','StarNet SHA locked'); A.eq(locks.sources.agent_lightning.sha,'7fd96d71cea423948c7b2db41c8fd01ecd1bb3b9','Lightning SHA locked'); A.eq(locks.sources.terabithia.sha,'c4996f90b8c5e2d357076591f291ecd52f7596b0','Terabithia SHA locked');
const nodes=[]; for(const area of ['map/watchers','map/fleet','map/data']) for(const f of fs.readdirSync(path.join(root,area))) nodes.push(fs.readFileSync(path.join(root,area,f),'utf8'));
for(const s of nodes) for(const field of ['type:','source:','truth_status:','sensitivity:','consumes:','produces:']) A.ok(s.includes(field),'node field '+field);
const s4=fs.readFileSync(path.join(root,'_templates/watch-run/04_propose/CONTEXT.md'),'utf8'); A.ok(s4.includes('../02_verify/output/verified.json')&&s4.includes('../03_cross-examine/output/disagreements.json'),'proposal lineage names both reproducible inputs');
const findingDir=path.join(root,'findings'); const indexed=fs.readFileSync(path.join(findingDir,'_index.jsonl'),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse); const records=fs.readdirSync(path.join(findingDir,'open')).filter(f=>f.endsWith('.json')).sort(); A.eq(indexed.length,records.length,'index row count matches finding records'); for(const name of records) A.ok(validateFinding(JSON.parse(fs.readFileSync(path.join(findingDir,'open',name)))),'finding conforms '+name); const before=fs.readFileSync(path.join(findingDir,'_index.jsonl'),'utf8'); generateFindingIndex(findingDir); A.eq(fs.readFileSync(path.join(findingDir,'_index.jsonl'),'utf8'),before,'finding index generator is deterministic');
A.ok(fs.readFileSync('infrastructure/terabithia/contract.md','utf8').includes('Mutation methods and bearer-token handling are absent'),'read-only boundary explicit'); A.report();
