'use strict';
const assert=require('node:assert');
const fs=require('node:fs');
const workflow=fs.readFileSync('.github/workflows/pauli-icm-live-watch.yml','utf8');
const runner=fs.readFileSync('scripts/pauli-icm/run-live-watch.js','utf8');
let n=0; const ok=(v,m)=>(assert.ok(v,m),n++);
ok(workflow.includes("cron: '23 */6 * * *'"),'six-hour schedule');
ok(workflow.includes('permissions:\n  contents: read'),'read-only token permission');
ok(workflow.includes('timeout-minutes: 5'),'bounded runtime');
ok(workflow.includes('cancel-in-progress: false'),'no evidence-destroying cancellation');
ok(workflow.includes('retention-days: 30'),'bounded artifact retention');
ok(!/secrets\./.test(workflow),'no secret injection');
ok(runner.includes("const HEALTH_URL = 'https://api.thepaulieffect.com/terabithia/health'"),'exact public source');
ok(runner.includes("mode: 'live-read-only'"),'live read-only mode');
ok(runner.includes('expected HTTP 401'),'protected routes fail closed');
ok(runner.includes('coverage_limit'),'honest coverage limit');
ok(runner.includes('trust_limit'),'honest receipt trust limit');
ok(runner.includes('cost_usd: 0'),'zero-cost receipt');
console.log(`tests: OK (${n} assertions)`);
